// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Make sure the type TeamMember runs hooks after queries
var _ bob.HookableType = &TeamMember{}

// Make sure the type TeamSetting runs hooks after queries
var _ bob.HookableType = &TeamSetting{}

// Make sure the type Team runs hooks after queries
var _ bob.HookableType = &Team{}

// Make sure the type UserSetting runs hooks after queries
var _ bob.HookableType = &UserSetting{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[json.RawMessage])(nil)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[json.RawMessage])
