// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// User is an object representing the database table.
type User struct {
	ID           string              `db:"id,pk" json:"id"`
	Email        string              `db:"email" json:"email"`
	PasswordHash string              `db:"password_hash" json:"password_hash"`
	FirstName    null.Val[string]    `db:"first_name" json:"first_name"`
	LastName     null.Val[string]    `db:"last_name" json:"last_name"`
	Role         string              `db:"role" json:"role"`
	Phone        null.Val[string]    `db:"phone" json:"phone"`
	IsActive     null.Val[bool]      `db:"is_active" json:"is_active"`
	LastLogin    null.Val[time.Time] `db:"last_login" json:"last_login"`
	CreatedAt    time.Time           `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time           `db:"updated_at" json:"updated_at"`

	R userR `db:"-" json:"-"`
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users")

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	TeamMembers TeamMemberSlice `json:"TeamMembers"` // team_members.team_members_user_id_fkey
	UserSetting *UserSetting    `json:"UserSetting"` // user_settings.user_settings_user_id_fkey
}

type userColumnNames struct {
	ID           string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	Role         string
	Phone        string
	IsActive     string
	LastLogin    string
	CreatedAt    string
	UpdatedAt    string
}

var UserColumns = buildUserColumns("users")

type userColumns struct {
	tableAlias   string
	ID           psql.Expression
	Email        psql.Expression
	PasswordHash psql.Expression
	FirstName    psql.Expression
	LastName     psql.Expression
	Role         psql.Expression
	Phone        psql.Expression
	IsActive     psql.Expression
	LastLogin    psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		Email:        psql.Quote(alias, "email"),
		PasswordHash: psql.Quote(alias, "password_hash"),
		FirstName:    psql.Quote(alias, "first_name"),
		LastName:     psql.Quote(alias, "last_name"),
		Role:         psql.Quote(alias, "role"),
		Phone:        psql.Quote(alias, "phone"),
		IsActive:     psql.Quote(alias, "is_active"),
		LastLogin:    psql.Quote(alias, "last_login"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type userWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, string]
	Email        psql.WhereMod[Q, string]
	PasswordHash psql.WhereMod[Q, string]
	FirstName    psql.WhereNullMod[Q, string]
	LastName     psql.WhereNullMod[Q, string]
	Role         psql.WhereMod[Q, string]
	Phone        psql.WhereNullMod[Q, string]
	IsActive     psql.WhereNullMod[Q, bool]
	LastLogin    psql.WhereNullMod[Q, time.Time]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:           psql.Where[Q, string](cols.ID),
		Email:        psql.Where[Q, string](cols.Email),
		PasswordHash: psql.Where[Q, string](cols.PasswordHash),
		FirstName:    psql.WhereNull[Q, string](cols.FirstName),
		LastName:     psql.WhereNull[Q, string](cols.LastName),
		Role:         psql.Where[Q, string](cols.Role),
		Phone:        psql.WhereNull[Q, string](cols.Phone),
		IsActive:     psql.WhereNull[Q, bool](cols.IsActive),
		LastLogin:    psql.WhereNull[Q, time.Time](cols.LastLogin),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var UserErrors = &userErrors{
	ErrUniqueEmail: &UniqueConstraintError{s: "users_email_key"},
}

type userErrors struct {
	ErrUniqueEmail *UniqueConstraintError
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID           omit.Val[string]        `db:"id,pk" json:"id"`
	Email        omit.Val[string]        `db:"email" json:"email"`
	PasswordHash omit.Val[string]        `db:"password_hash" json:"password_hash"`
	FirstName    omitnull.Val[string]    `db:"first_name" json:"first_name"`
	LastName     omitnull.Val[string]    `db:"last_name" json:"last_name"`
	Role         omit.Val[string]        `db:"role" json:"role"`
	Phone        omitnull.Val[string]    `db:"phone" json:"phone"`
	IsActive     omitnull.Val[bool]      `db:"is_active" json:"is_active"`
	LastLogin    omitnull.Val[time.Time] `db:"last_login" json:"last_login"`
	CreatedAt    omit.Val[time.Time]     `db:"created_at" json:"created_at"`
	UpdatedAt    omit.Val[time.Time]     `db:"updated_at" json:"updated_at"`
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.Email.IsUnset() {
		vals = append(vals, "email")
	}

	if !s.PasswordHash.IsUnset() {
		vals = append(vals, "password_hash")
	}

	if !s.FirstName.IsUnset() {
		vals = append(vals, "first_name")
	}

	if !s.LastName.IsUnset() {
		vals = append(vals, "last_name")
	}

	if !s.Role.IsUnset() {
		vals = append(vals, "role")
	}

	if !s.Phone.IsUnset() {
		vals = append(vals, "phone")
	}

	if !s.IsActive.IsUnset() {
		vals = append(vals, "is_active")
	}

	if !s.LastLogin.IsUnset() {
		vals = append(vals, "last_login")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.Email.IsUnset() {
		t.Email, _ = s.Email.Get()
	}
	if !s.PasswordHash.IsUnset() {
		t.PasswordHash, _ = s.PasswordHash.Get()
	}
	if !s.FirstName.IsUnset() {
		t.FirstName, _ = s.FirstName.GetNull()
	}
	if !s.LastName.IsUnset() {
		t.LastName, _ = s.LastName.GetNull()
	}
	if !s.Role.IsUnset() {
		t.Role, _ = s.Role.Get()
	}
	if !s.Phone.IsUnset() {
		t.Phone, _ = s.Phone.GetNull()
	}
	if !s.IsActive.IsUnset() {
		t.IsActive, _ = s.IsActive.GetNull()
	}
	if !s.LastLogin.IsUnset() {
		t.LastLogin, _ = s.LastLogin.GetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 11)
		if s.ID.IsUnset() {
			vals[0] = psql.Raw("DEFAULT")
		} else {
			vals[0] = psql.Arg(s.ID)
		}

		if s.Email.IsUnset() {
			vals[1] = psql.Raw("DEFAULT")
		} else {
			vals[1] = psql.Arg(s.Email)
		}

		if s.PasswordHash.IsUnset() {
			vals[2] = psql.Raw("DEFAULT")
		} else {
			vals[2] = psql.Arg(s.PasswordHash)
		}

		if s.FirstName.IsUnset() {
			vals[3] = psql.Raw("DEFAULT")
		} else {
			vals[3] = psql.Arg(s.FirstName)
		}

		if s.LastName.IsUnset() {
			vals[4] = psql.Raw("DEFAULT")
		} else {
			vals[4] = psql.Arg(s.LastName)
		}

		if s.Role.IsUnset() {
			vals[5] = psql.Raw("DEFAULT")
		} else {
			vals[5] = psql.Arg(s.Role)
		}

		if s.Phone.IsUnset() {
			vals[6] = psql.Raw("DEFAULT")
		} else {
			vals[6] = psql.Arg(s.Phone)
		}

		if s.IsActive.IsUnset() {
			vals[7] = psql.Raw("DEFAULT")
		} else {
			vals[7] = psql.Arg(s.IsActive)
		}

		if s.LastLogin.IsUnset() {
			vals[8] = psql.Raw("DEFAULT")
		} else {
			vals[8] = psql.Arg(s.LastLogin)
		}

		if s.CreatedAt.IsUnset() {
			vals[9] = psql.Raw("DEFAULT")
		} else {
			vals[9] = psql.Arg(s.CreatedAt)
		}

		if s.UpdatedAt.IsUnset() {
			vals[10] = psql.Raw("DEFAULT")
		} else {
			vals[10] = psql.Arg(s.UpdatedAt)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.Email.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if !s.PasswordHash.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password_hash")...),
			psql.Arg(s.PasswordHash),
		}})
	}

	if !s.FirstName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "first_name")...),
			psql.Arg(s.FirstName),
		}})
	}

	if !s.LastName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_name")...),
			psql.Arg(s.LastName),
		}})
	}

	if !s.Role.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "role")...),
			psql.Arg(s.Role),
		}})
	}

	if !s.Phone.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "phone")...),
			psql.Arg(s.Phone),
		}})
	}

	if !s.IsActive.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if !s.LastLogin.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_login")...),
			psql.Arg(s.LastLogin),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			SelectWhere.Users.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Users.Query(
		SelectWhere.Users.ID.EQ(IDPK),
		sm.Columns(Users.Columns().Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Users.Query(
		SelectWhere.Users.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the User
func (o *User) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		SelectWhere.Users.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ         string
	TeamMembers func(context.Context) modAs[Q, teamMemberColumns]
	UserSetting func(context.Context) modAs[Q, userSettingColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ:         typ,
		TeamMembers: usersJoinTeamMembers[Q](cols, typ),
		UserSetting: usersJoinUserSetting[Q](cols, typ),
	}
}

func usersJoinTeamMembers[Q dialect.Joinable](from userColumns, typ string) func(context.Context) modAs[Q, teamMemberColumns] {
	return func(ctx context.Context) modAs[Q, teamMemberColumns] {
		return modAs[Q, teamMemberColumns]{
			c: TeamMemberColumns,
			f: func(to teamMemberColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TeamMembers.Name().As(to.Alias())).On(
						to.UserID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

func usersJoinUserSetting[Q dialect.Joinable](from userColumns, typ string) func(context.Context) modAs[Q, userSettingColumns] {
	return func(ctx context.Context) modAs[Q, userSettingColumns] {
		return modAs[Q, userSettingColumns]{
			c: UserSettingColumns,
			f: func(to userSettingColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserSettings.Name().As(to.Alias())).On(
						to.UserID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

// TeamMembers starts a query for related objects on team_members
func (o *User) TeamMembers(mods ...bob.Mod[*dialect.SelectQuery]) TeamMembersQuery {
	return TeamMembers.Query(append(mods,
		sm.Where(TeamMemberColumns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) TeamMembers(mods ...bob.Mod[*dialect.SelectQuery]) TeamMembersQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.ID)
	}

	return TeamMembers.Query(append(mods,
		sm.Where(psql.Group(TeamMemberColumns.UserID).In(PKArgs...)),
	)...)
}

// UserSetting starts a query for related objects on user_settings
func (o *User) UserSetting(mods ...bob.Mod[*dialect.SelectQuery]) UserSettingsQuery {
	return UserSettings.Query(append(mods,
		sm.Where(UserSettingColumns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) UserSetting(mods ...bob.Mod[*dialect.SelectQuery]) UserSettingsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.ID)
	}

	return UserSettings.Query(append(mods,
		sm.Where(psql.Group(UserSettingColumns.UserID).In(PKArgs...)),
	)...)
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "TeamMembers":
		rels, ok := retrieved.(TeamMemberSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.TeamMembers = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "UserSetting":
		rel, ok := retrieved.(*UserSetting)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UserSetting = rel

		if rel != nil {
			rel.R.User = o
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

func ThenLoadUserTeamMembers(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserTeamMembers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserTeamMembers", retrieved)
		}

		err := loader.LoadUserTeamMembers(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserTeamMembers loads the user's TeamMembers into the .R struct
func (o *User) LoadUserTeamMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TeamMembers = nil

	related, err := o.TeamMembers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.TeamMembers = related
	return nil
}

// LoadUserTeamMembers loads the user's TeamMembers into the .R struct
func (os UserSlice) LoadUserTeamMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	teamMembers, err := os.TeamMembers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.TeamMembers = nil
	}

	for _, o := range os {
		for _, rel := range teamMembers {
			if o.ID != rel.UserID {
				continue
			}

			rel.R.User = o

			o.R.TeamMembers = append(o.R.TeamMembers, rel)
		}
	}

	return nil
}

func PreloadUserUserSetting(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*UserSetting, UserSettingSlice](orm.Relationship{
		Name: "UserSetting",
		Sides: []orm.RelSide{
			{
				From: TableNames.Users,
				To:   TableNames.UserSettings,
				FromColumns: []string{
					ColumnNames.Users.ID,
				},
				ToColumns: []string{
					ColumnNames.UserSettings.UserID,
				},
			},
		},
	}, UserSettings.Columns().Names(), opts...)
}

func ThenLoadUserUserSetting(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserUserSetting(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserUserSetting", retrieved)
		}

		err := loader.LoadUserUserSetting(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserUserSetting loads the user's UserSetting into the .R struct
func (o *User) LoadUserUserSetting(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserSetting = nil

	related, err := o.UserSetting(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.User = o

	o.R.UserSetting = related
	return nil
}

// LoadUserUserSetting loads the user's UserSetting into the .R struct
func (os UserSlice) LoadUserUserSetting(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userSettings, err := os.UserSetting(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range userSettings {
			if o.ID != rel.UserID {
				continue
			}

			rel.R.User = o

			o.R.UserSetting = rel
			break
		}
	}

	return nil
}

func insertUserTeamMembers0(ctx context.Context, exec bob.Executor, teamMembers1 []*TeamMemberSetter, user0 *User) (TeamMemberSlice, error) {
	for i := range teamMembers1 {
		teamMembers1[i].UserID = omit.From(user0.ID)
	}

	ret, err := TeamMembers.Insert(bob.ToMods(teamMembers1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserTeamMembers0: %w", err)
	}

	return ret, nil
}

func attachUserTeamMembers0(ctx context.Context, exec bob.Executor, count int, teamMembers1 TeamMemberSlice, user0 *User) (TeamMemberSlice, error) {
	setter := &TeamMemberSetter{
		UserID: omit.From(user0.ID),
	}

	err := teamMembers1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserTeamMembers0: %w", err)
	}

	return teamMembers1, nil
}

func (user0 *User) InsertTeamMembers(ctx context.Context, exec bob.Executor, related ...*TeamMemberSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	teamMembers1, err := insertUserTeamMembers0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.TeamMembers = append(user0.R.TeamMembers, teamMembers1...)

	for _, rel := range teamMembers1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachTeamMembers(ctx context.Context, exec bob.Executor, related ...*TeamMember) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	teamMembers1 := TeamMemberSlice(related)

	_, err = attachUserTeamMembers0(ctx, exec, len(related), teamMembers1, user0)
	if err != nil {
		return err
	}

	user0.R.TeamMembers = append(user0.R.TeamMembers, teamMembers1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserUserSetting0(ctx context.Context, exec bob.Executor, userSetting1 *UserSettingSetter, user0 *User) (*UserSetting, error) {
	userSetting1.UserID = omit.From(user0.ID)

	ret, err := UserSettings.Insert(userSetting1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserUserSetting0: %w", err)
	}

	return ret, nil
}

func attachUserUserSetting0(ctx context.Context, exec bob.Executor, count int, userSetting1 *UserSetting, user0 *User) (*UserSetting, error) {
	setter := &UserSettingSetter{
		UserID: omit.From(user0.ID),
	}

	err := userSetting1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserUserSetting0: %w", err)
	}

	return userSetting1, nil
}

func (user0 *User) InsertUserSetting(ctx context.Context, exec bob.Executor, related *UserSettingSetter) error {
	userSetting1, err := insertUserUserSetting0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.UserSetting = userSetting1

	userSetting1.R.User = user0

	return nil
}

func (user0 *User) AttachUserSetting(ctx context.Context, exec bob.Executor, userSetting1 *UserSetting) error {
	var err error

	_, err = attachUserUserSetting0(ctx, exec, 1, userSetting1, user0)
	if err != nil {
		return err
	}

	user0.R.UserSetting = userSetting1

	userSetting1.R.User = user0

	return nil
}
